apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: adapter-busybox
  name: adapter-busybox
spec:
  containers:
  - image: busybox
    name: adapter-busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
