apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx
    name: backend
    resources: {}
    envFrom:
      - configMapRef:
          name: db-config
          key: config.txt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
