apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: nginx-secret
    image: nginx
    env:
      - name: MY_VARIABLE
        valueFrom:
          secretKeyRef:
            name: some-secret
            key: key2
  restartPolicy: Never
